### ISSUE TITLE
Can no longer add TV to Webthings Gateway

### ISSUE THREAD

**Issue by malceore** [mozilla-iot/lg-tv-adapter#13]
Hello, I previously was able to connect my LG Smart TV to my Webthings Gateway using this plugin, but I am currently upgrading from 0.8 to 0.12 and re-adding all my smart things. I add the latest version of the plugin, v0.3.5, to my configuration using the add-on menu and then have attempted to add my TV. I see the pop-up that informs me about seeing numbers on my TV, but my TV never presents any sort of pop-up and the service never gives me any place to enter them into. So far I have tried resetting my whole network, wiping my TV, manually adding the IP of the TV to the configuration and re-adding the plugin. Some additional information; I am using the webthings docker container, from the connected server I can ping the TV no problem and I was able to download an app for my phone and pair that with the TV just fine.

Here is the output when I click the plus to add my device, I feel as though it should be outputting more:
`2020-09-18 15:36:51.853 INFO   : Opened a new things socket
2020-09-18 15:36:52.087 INFO   : About to call startPairing on LgTvAdapter
2020-09-18 15:37:52.093 INFO   : Pairing timeout
2020-09-18 15:37:52.095 INFO   : lg-tv-adapter: Adapter: LgTvAdapter id lg-tv-adapter pairing cancelled
`

Does one need to forward a certain port for this plugin to work in docker? Is there a way to get more debugging information from gateway or just the plugin itself?  I really, really enjoyed this addition to my smart home so I am willing to try many different things to get it to work.

Thanks in advance!

**Comment by mrstegeman** [comment]
Your docker container needs to be able to do SSDP lookups. If you run in host networking mode, things _should_ work fine, assuming you don't have another firewall set up.

**Comment by malceore** [comment]
My mistake, feel free to close this up. Docker install is messed up. Cloning 0.11.0 and installing the application works without issue for me.
